version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    
  whoami:
    container_name: "http-echo"
    image: "whoami"
    build: 
      context: .
      dockerfile: ./dockerfiles/whoami.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=(Host(`127.0.0.1`) || Host(`localhost`) && PathPrefix(`/hello/`))"
      - "traefik.http.routers.whoami.entrypoints=web"