---
- name: Container pipeline
  hosts: all
  become: yes

  tasks:
    - name: Removing pakcages conflicting with Docker
      ansible.builtin.apt:
        name:
          - docker 
          - docker-engine 
          - docker.io 
          - containerd 
          - runc
        state: absent

    - name: Installing necessary packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Adding Docker Engine repo key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Adding Docker Engine repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Installing Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-compose-plugin
        state: present

    - name: Installing python3 and python3-pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Installing python modules docker and docker-compose
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose
        state: present
